Website = "https://github.com/Sarwarhridoy4/github-ssh-manager"

[Details]
Icon = "icon.png"
Name = "GitHub SSH Manager"
ID = "com.sarwarhridoy4.github-ssh-manager"
Version = "2.5"
Build = 13

[LinuxAndBSD]
GenericName = "SSH Key Manager"
Categories = ["Development", "Network", "Utility"]
Comment = "Manage SSH keys for GitHub accounts"
Keywords = ["ssh", "github", "key", "manager", "git", "security"]
